### ISSUE TITLE
token refresh failed/

### ISSUE THREAD

**Issue by conge** [u8sand/fitbit-dump#2]
4 days after the first time I run the code, I run it again with the evn file generated then, but failed at auth_refresh.

the error message is 
```
AssertionError: {"errors":[{"errorType":"invalid_client","message":"Invalid authorization header. Client id invalid. Visit https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit Web API authorization process."}],"success":false}

```

I was able to work around it by deleting the .env file and rerunning the `init`

but would like to report the error.

**Comment by u8sand** [comment]
@conge I think this is working with my commit (adding the client_id to the refresh token payload), but I guess i'll need to wait 8 hours to really try it (just tried it by refreshing anyway).

In the future, easier than deleting `.env` is just removing `FITBIT_AUTHORIZATION` from `.env` and running init keeping all the defaults. Might consider adding a `--force-auth` option that does that basically.

It's also possible this is actually just the refresh token itself expiring, in which case, we can consider falling back to the standard flow if refresh fails.

**Comment by u8sand** [comment]
A week later, this worked successfully in my test.
